apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ../../../base/frontend
  - ingress-tailscale1.yaml

patches:
  - path: patch-nginx.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - default.conf=nginx/default.conf
      - rewrite-mixed-content.js=rewrite-mixed-content.js

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/mihaicatalin22/questify-frontend
    newTag: feat-cicd2-03eb73f
