apiVersion: apps/v1
kind: Deployment
metadata:
  name: questify-frontend
  labels: { app: questify-frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: questify-frontend }
  template:
    metadata:
      labels: { app: questify-frontend }
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mihiacatalin22/questify-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 20
            periodSeconds: 20
