apiVersion: v1
kind: Service
metadata:
  name: questify-frontend
  labels: { app: questify-frontend }
spec:
  type: ClusterIP
  selector:
    app: questify-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
