apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../base/user-service
images:
- name: ghcr.io/mihaicatalin22/questify-user-service
  newTag: feat-cicd2-1c4d8c1
patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: user-service
    namespace: default
  path: patch-env.yaml
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: user-service
    namespace: default
  path: patch-oidc-vm.yaml
