- op: replace
  path: /spec/template/spec/containers/0/env/11/value
  value: https://questify-1.tail03c40b.ts.net/auth/realms/questify
- op: replace
  path: /spec/template/spec/containers/0/env/9/value
  value: https://questify-1.tail03c40b.ts.net/auth/realms/questify
- op: replace
  path: /spec/template/spec/containers/0/env/10/value
  value: http://keycloak:8080/auth/realms/questify/protocol/openid-connect/certs
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
    value: http://keycloak:8080/auth/realms/questify/protocol/openid-connect/certs
