apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/proof-service
images:
  - name: ghcr.io/mihaicatalin22/questify-proof-service
    newTag: feat-cicd2-1e680cb
patches:
  - path: patch-env.yaml