apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/user-service
images:
  - name: ghcr.io/MihaiCatalin22/questify-user-service
    newTag: main-abcdef0
