apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/user-service
images:
  - name: ghcr.io/mihaicatalin22/questify-user-service
    newTag: feat-cicd2-8d98a6c
patches:
  - path: patch-env.yaml