apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/quest-service
images:
  - name: ghcr.io/mihaicatalin22/questify-quest-service
    newTag: feat-cicd2-f5be2ef
patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: quest-service
