apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../base/submission-service
images:
  - name: ghcr.io/mihaicatalin22/questify-submission-service
    newTag: feat-cicd2-f5be2ef

patches:
  - path: patch-env.yaml

