apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: questify
resources:
  - ../../../base/submission-service
images:
  - name: ghcr.io/MihaiCatalin22/questify-submission-service
    newTag: latest
