apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ../../../base/submission-service

images:
  - name: ghcr.io/mihaicatalin22/questify-submission-service
    newTag: feat-cicd2-0c01284

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: submission-service
      namespace: default
    path: patch-env.yaml
