- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SECURITY_INTERNAL_TOKEN
    valueFrom:
      secretKeyRef:
        name: internal-token
        key: token

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: INTERNAL_TOKEN
    valueFrom:
      secretKeyRef:
        name: internal-token
        key: token

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SERVER_FORWARD_HEADERS_STRATEGY
    value: framework

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SERVER_TOMCAT_USE_RELATIVE_REDIRECTS
    value: "true"
