apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../base/quest-service
images:
- name: ghcr.io/mihaicatalin22/questify-quest-service
  newTag: feat-cicd2-66d6e73
patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: quest-service
    namespace: default
  path: patch-env.yaml
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: quest-service
    namespace: default
  path: patch-resources.yaml
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: quest-service
    namespace: default
  path: patch-oidc-vm.yaml
