apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: quest-service-success-rate
  namespace: default
spec:
  args:
    - name: prometheus-url
    - name: job
    - name: namespace
  metrics:
    - name: http-success-rate
      interval: 30s
      count: 4
      failureLimit: 1
      successCondition: result[0] >= 0.99
      provider:
        prometheus:
          address: "{{args.prometheus-url}}"
          query: |
            sum(rate(http_server_requests_seconds_count{namespace="{{args.namespace}}", job="{{args.job}}", status!~"5..", uri!~"/actuator.*"}[2m]))
            /
            sum(rate(http_server_requests_seconds_count{namespace="{{args.namespace}}", job="{{args.job}}", uri!~"/actuator.*"}[2m]))
