apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: submission-service-5xx-rate
  namespace: default
spec:
  metrics:
    - name: http-5xx-rate
      interval: 30s
      count: 4
      failureLimit: 1
      consecutiveErrorLimit: 10
      successCondition: result[0] <= 0
      provider:
        prometheus:
          address: http://kps-kube-prometheus-stack-prometheus.monitoring.svc:9090
          query: |
            sum(rate(http_server_requests_seconds_count{namespace="default", job="submission-service", status=~"5..", uri!~"/actuator.*"}[2m])) or vector(0)
